name: Auto-download resume from overleaf
description: Fetches a resume pdf from an overleaf and commits it to the repository.
author: sbrjt

inputs:
  overleaf_url:
    required: true
    description: Read-url from overleaf
  github_token:
    required: true
    description: GitHub token for authentication
  gdrive_link:
    description: Google drive link with edit permission

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create requirements.txt
      run: echo "selenium" > requirements.txt
      shell: bash 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: 'pip'

    - name: Install selenium
      run: pip install -r requirements.txt
      shell: bash

    - name: Run Selenium script
      id: script
      run: python "${GITHUB_ACTION_PATH}/selenium_script.py" "${{ inputs.overleaf_url }}"
      shell: bash

    - name: Commit the PDF file
      id: set-output
      if: steps.script.outputs.skip != 'True'
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add resume.tex resume.pdf
        git commit -m "Resume updated"
        git push
      env:
        GITHUB_TOKEN: '${{ inputs.github_token }}'
      shell: bash

    - name: Upload to google drive
      id: drive_upload
      if: ${{ inputs.gdrive_link != '' && steps.script.outputs.skip != 'True'}}
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://overleaf-resume-downloader.onrender.com
        method: POST
        data: '{"link": "${{ inputs.gdrive_link }}"}'
        files: '{"file": "resume.pdf"}'

    - if: steps.drive_upload.outcome == 'success' 
      run: echo ${{ steps.drive_upload.outputs.response }}

branding:
  icon: 'book'
  color: 'green'
