name: Auto-download resume from overleaf
description: Fetches a resume pdf from an overleaf and commits it to the repository.
author: sbrjt

inputs:
  overleaf_url:
    required: true
    description: Read-url from overleaf
  github_token:
    required: true
    description: GitHub token for authentication

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install selenium
      run: pip install selenium
      shell: bash

    - name: Run Selenium script
      id: check-flag
      run: |
        mkdir temp
        python "${GITHUB_ACTION_PATH}/selenium_script.py" "${{ inputs.overleaf_url }}"
        rm -rf temp
      shell: bash

    - name: Commit the PDF file
      id: set-output
      if: steps.check-flag.outputs.skip != 'True'
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add resume.tex resume.pdf
        git commit -m "Resume updated"
        git push
      env:
        GITHUB_TOKEN: '${{ inputs.github_token }}'
      shell: bash

branding:
  icon: 'book'
  color: 'green'
