name: Test
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./ # Uses action.yml in the root directory
        with:
          overleaf_url: 'https://www.overleaf.com/read/nsgsskwncdmy#a859ac'
          github_token: ${{ secrets.GITHUB_TOKEN }}
